### PR TITLE
GitHub Actions for CI

### PR DESCRIPTION
**Pull request by ekilmer**
Should not be merged until Travis is fixed, but this should work as a replacement when that happens.

There are a few commits in this PR, but basically, https://github.com/trailofbits/manticore-examples/commit/a15746158f3a42edfadb0378e0cac6c005ce7dd4 is what should be merged to `master`.

~~I'm thinking `.travis.yml` should be removed in a different PR, once we ensure Github Actions is working as intended. I think redirecting the CI badge in the README should also be done in the PR where Travis is removed.~~ Done.

TODO:
- [x] Only run Github Actions on `master` (revert https://github.com/trailofbits/manticore-examples/commit/aa21484fceef61cec1365781078b85f33368d40c)
- [x] Only install Manticore from PyPI and `master` branch on Git, and allow fails when running against Manticore `master` branch (revert https://github.com/trailofbits/manticore-examples/commit/34c0315b30bba59456a4f94e23e8009a1e1310d7)
- [x] ~~Rebase on `master` when the fix for `polyswarm_challenge` in #35 is merged (remove https://github.com/trailofbits/manticore-examples/commit/ff47170d0834b5342d93820e637f88739be13589)~~ (Edit: Just removed the commit without rebasing. Needed to get this PR merged before fixing the challenge.)

Note: I'll request a real review from you, @reaperhulk , after the TODOs and dependent PR are done and merged :)

### CODE REVIEW

**Comment by reaperhulk** [comment]
Are we expecting tests to pass now or is there still an outstanding bug we need to separately fix?

**Comment by ekilmer** [comment]
> Are we expecting tests to pass now

No. There is still 1 outlying test failure that is being tracked, but it seems Travis is no longer running on `master`, so I thought we should work on merging this now.

**Comment by ehennenfent** [comment]
https://github.com/trailofbits/manticore/pull/1577 needs to be merged and make it into a PyPi build before this will pass. There's still some ongoing discussion regarding the behavior of the smtlib visitor API.

**Comment by reaperhulk** [comment]
Fair! Hopefully we'll see green here soon once that fix gets merged (this CI pulls directly from git so no need to do a pypi release to fix it right?)

**Comment by ekilmer** [comment]
> this CI pulls directly from git

This is correct.

> so no need to do a pypi release to fix it right

With the way I set up the CI, the primary indicator of success is from installing through PyPI. Unfortunately, if the PyPI build fails before the `master` job, then the `master` job is killed prematurely 😞 https://github.com/trailofbits/manticore-examples/commit/a2bac8295da0383f3362c380c13a682c8c6831d5/checks?check_suite_id=389151446#step:5:10 

But, it looks like both PyPI and `master` jobs take a similar amount of time, because this one finished in the way we expected https://github.com/trailofbits/manticore-examples/commit/c8fa19235accd8177a988c0f1d0588563c82fa59/checks?check_suite_id=389167785

**Pull request merged**
